package assign4;

import java.io.Serializable;
import java.util.Date;

/**
 * Message class that implements Serializable.
 * @author fhj
 */
public class Message implements Serializable {

	/**
	 * Who wrote the message.
	 */
	private User user;
	private String msgText;
	private Date date;
    
	/**
	 * This attribute links a response message (from an employee) to an 
     * original message (from a customer).
	 * For messages generated by customers, the value of this variable will be 
     * null.
	 */
	private Message inResponseTo = null;

    /**
     * Returns user.
     * @return 
     */
    public User getUser() {
      return user;
    }

    /**
     * Sets user.
     * @param user 
     */
    public void setUser(User user) {
      this.user = user;
    }

    /**
     * Returns msgText.
     * @return 
     */
    public String getMsgText() {
      return msgText;
    }

    /**
     * Sets msgText.
     * @param msgText 
     */
    public void setMsgText(String msgText) {
      this.msgText = msgText;
    }

    /**
     * Returns date.
     * @return 
     */
    public Date getDate() {
      return date;
    }

    /**
     * Sets date.
     * @param date 
     */
    public void setDate(Date date) {
      this.date = date;
    }

    /**
     * Returns inResponseTo.
     * @return 
     */
    public Message getInResponseTo() {
      return inResponseTo;
    }

    /**
     * Sets inResponseTo.
     * @param inResponseTo 
     */
    public void setInResponseTo(Message inResponseTo) {
      this.inResponseTo = inResponseTo;
    }
    
    /**
     * Overrides toString to print the messages.
     * @return 
     */
    @Override
    public String toString() {
        return "\nMessage {ID: "+ user.getId() + "Name: " + user.getName() + ", Message: " 
                + msgText + " date:" + date +  " In response to: " + inResponseTo + " }";
    }
}